#web 配置
server:
  port: 8080
  servlet:
    context-path: /hc

# mysql 配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_check?characterEncoding=utf-8
    username: root
    password: 12345aB!

# mybatis 配置
mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml

# 日志
logging:
  level:
    org.springframework: info
    com.bingo.server.mapper: info
    org.apache.ibatis.logging.stdout: debug

    